// This file is generated by Slice Machine. Update with care!

import CurriculumVitae from './CurriculumVitae';
import Text from './Text';

export {
	CurriculumVitae,
	Text,
};

export const components = {
	curriculum_vitae: CurriculumVitae,
	text: Text,
};
